import Controller from '@ember/controller';
import { set } from '@ember/object';
import { inject as service } from '@ember/service';

export default Controller.extend({
    toastr: service('toast'),
    router: service(),

    actions: {
        async save() {
            try {
                if (this.model.company && this.model.occupation) {
                    let recruiter = {
                        name: this.recruiterName,
                        email: this.recruiterMail,
                        tel: this.recruiterTel,
                        fax: this.recruiterFax
                    };
                    set(this.model, 'recruiter', recruiter);
                    await this.model.save();
                    set(this, 'recruiterName', '');
                    set(this, 'recruiterMail', '');
                    set(this, 'recruiterTel', '');
                    set(this, 'recruiterFax', '');
                    this.router.transitionTo('applications')
                } else {
                    this.toastr.error('Please add company and occupation', 'Warning');
                }
            } catch (error) {
                console.log(error);
            }
        },
        redirect() {
            this.model.deleteRecord();
            this.router.transitionTo('applications')
        }
    },
   async init() {

        this._super(...arguments);
        this.companies = await [
            'Apple', 'Microsoft', 'Amazon', 'Alphabet', 'Berkshire Hathaway', 'Facebook', 'Alibaba', 'Tencent Holdings', 'JPMorgan Chase', 'Johnson & Johnson', 'Visa', 'ExxonMobil', 'ICBC', 'Walmart', 'Bank of America', 'Nestle', 'Samsung Electronics', 'Procter & Gamble', 'Royal Dutch Shell', 'Intel', 'Cisco Systems', 'Mastercard', 'Verizon Communications', 'Walt Disney', 'AT&T', 'Chevron', 'Home Depot', 'China Constructionbank', 'Nike', 'Taiwan Semiconductor', 'Roche Holding', 'Ping An Insurance Group', 'Pfizer', 'Wells Fargo', 'Boeing', 'UnitedHealth Group', 'Coca-Cola', 'PetroChina', 'China Mobile', 'Agriculturalbank of China', 'Comcast', 'Merck & Co', 'Oracle', 'PepsiCo', 'Toyota Motor', 'Netlix', 'Unilever', 'Total', 'LOreal', 'SAP', 'LinkedIn', 'Google', 'Southwest Airlines', 'Salesforce', 'HubSpot', 'McKinsey & Company', 'Hilton', 'Cisco', 'Ultimate Software', 'Uber', 'Lyft', 'Tesla', 'Deloitte', 'McDonalds', 'PayPal', 'Honeywell International', 'Accenture', 'NVIDIA', 'Texas Instruments', 'Costco Wholesale', 'Allianz', 'Rio Tinto', 'Bayerische Motorwerke', 'AUDI', 'Daimler', 'Volkswagen' 
        ];

        this.statuses = await [
            'In Progress', 'Submitted', 'Cancelled', 'Offer', 'Denied', 'On-Site', 'Phone Screen', 'Coding Challenge'
        ]

        this.sources = await [
            'Indeed', 'LinkedIn', 'Employee', 'Recruiter', 'Google Search', 'Glassdoor'
        ]

        this.occupations = await [
            'accountant',
            'actor',
            'actuary',
            'administrative assistant',
            'administrative services manager',
            'advertising manager',
            'advertising sales agent',
            'aerospace engineer',
            'aerospace engineering technician',
            'agent',
            'agricultural engineer',
            'agricultural equipment operator',
            'agricultural worker',
            'air traffic controller',
            'aircraft service technician',
            'airline pilot',
            'architect',
            'architectural drafter',
            'architectural manager',
            'artist',
            'assembler',
            'athlete',
            'ATM machine repairer',
            'audio and video equipment technician',
            'audio-visual and multimedia collections specialist',
            'auditor',
            'author',
            'backend engineer',
            'bill and account collector',
            'billing and posting clerk',
            'biochemist',
            'biological technician',
            'biomedical engineer',
            'biophysicist',
            'broadcast news analyst',
            'broadcast technician',
            'budget analyst',
            'camera operator',
            'camera repairer',
            'chemical engineer',
            'chemical plant operator',
            'chemist',
            'chief executive',
            'chiropractor',
            'choreographer',
            'civil engineer',
            'civil engineering technician',
            'clinical laboratory technician',
            'clinical laboratory technologist',
            'clinical psychologist',
            'commercial diver',
            'commercial pilot',
            'commodities sales agent',
            'communications equipment operator',
            'communications teacher',
            'community association manager',
            'community service manager',
            'compensation and benefits manager',
            'compliance officer',
            'composer',
            'computer hardware engineer',
            'computer network architect',
            'computer operator',
            'computer programmer',
            'computer science teacher',
            'computer support specialist',
            'computer systems administrator',
            'computer systems analyst',
            'continuous mining machine operator',
            'cosmetologist',
            'credit analyst',
            'credit checker',
            'credit counselor',
            'criminal investigator',
            'criminal justice teacher',
            'data entry keyer',
            'database administrator',
            'delivery services driver',
            'designer',
            'desktop publisher',
            'economist',
            'editor',
            'electrical engineer',
            'engineer',
            'engineering manager',
            'engineering teacher',
            'environmental engineer',
            'environmental science teacher',
            'environmental scientist',
            'event planner',
            'executive administrative assistant',
            'executive secretary',
            'fashion designer',
            'financial analyst',
            'financial examiner',
            'financial manager',
            'financial services sales agent',
            'fitness studies teacher',
            'fitness trainer',
            'flight attendant',
            'food science technician',
            'food scientist',
            'frontend developer',
            'geographer',
            'geological engineer',
            'geological technician',
            'geoscientist',
            'graphic designer',
            'health and safety engineer',
            'health educator',
            'health information technician',
            'health services manager',
            'health specialties teacher',
            'healthcare social worker',
            'hearing officer',
            'historian',
            'host',
            'hostess',
            'human resources assistant',
            'human resources manager',
            'human service assistant',
            'illustrator',
            'industrial designer',
            'industrial engineer',
            'industrial engineering technician',
            'industrial machinery mechanic',
            'industrial production manager',
            'industrial truck operator',
            'industrial-organizational psychologist',
            'information clerk',
            'information research scientist',
            'information security analyst',
            'information systems manager',
            'inspector',
            'instructional coordinator',
            'instructor',
            'insulation worker',
            'insurance claims clerk',
            'insurance sales agent',
            'insurance underwriter',
            'interior designer',
            'internist',
            'interviewer',
            'investigator',
            'judicial law clerk',
            'kettle operator',
            'kiln operator',
            'kindergarten teacher',
            'law teacher',
            'lawyer',
            'legal assistant',
            'legal secretary',
            'legislator',
            'librarian',
            'library assistant',
            'library science teacher',
            'library technician',
            'licensed practical nurse',
            'licensed vocational nurse',
            'life scientist',
            'lifeguard',
            'management analyst',
            'marine engineer',
            'marine oiler',
            'market research analyst',
            'marketing manager',
            'marketing specialist',
            'materials engineer',
            'materials scientist',
            'mathematical science teacher',
            'mathematical technician',
            'mathematician',
            'mechanical door repairer',
            'mechanical drafter',
            'mechanical engineer',
            'mechanical engineering technician',
            'medical appliance technician',
            'medical assistant',
            'medical equipment preparer',
            'medical equipment repairer',
            'medical laboratory technician',
            'medical laboratory technologist',
            'medical records technician',
            'medical scientist',
            'medical secretary',
            'medical services manager',
            'medical transcriptionist',
            'microbiologist',
            'middle school teacher',
            'music director',
            'musician',
            'natural sciences manager',
            'network systems administrator',
            'news vendor',
            'nuclear engineer',
            'nuclear medicine technologist',
            'nuclear power reactor operator',
            'nuclear technician',
            'obstetrician',
            'operating engineer',
            'operations manager',
            'operations research analyst',
            'ophthalmic laboratory technician',
            'optician',
            'outdoor power equipment mechanic',
            'oven operator',
            'packaging machine operator',
            'paralegal',
            'paramedic',
            'pharmacist',
            'pharmacy technician',
            'photographic processing machine operator',
            'physical therapist aide',
            'physical therapist assistant',
            'physical therapist',
            'physician assistant',
            'physician',
            'physicist',
            'producer',
            'product owner',
            'product manager',
            'radio announcer',
            'real estate appraiser',
            'real estate broker',
            'real estate manager',
            'real estate sales agent',
            'sailor',
            'sales engineer',
            'sales manager',
            'sales representative',
            'sampler',
            'secretary',
            'securities sales agent',
            'security guard',
            'security system installer',
            'set designer',
            'ship captain',
            'ship engineer',
            'ship loader',
            'shipmate',
            'social science research assistant',
            'social sciences teacher',
            'social scientist',
            'social service assistant',
            'social service manager',
            'social work teacher',
            'social worker',
            'sociologist',
            'sociology teacher',
            'software developer',
            'software engineer',
            'sound engineering technician',
            'space scientist',
            'special education teacher',
            'speech-language pathologist',
            'sports performer',
            'stationary engineer',
            'statistical assistant',
            'statistician',
            'stock mover',
            'tamping equipment operator',
            'tax collector',
            'tax examiner',
            'tax preparer',
            'teacher',
            'technical writer',
            'techlead',
            'training and development manager',
            'training and development specialist',
            'veterinarian',
            'veterinary assistant',
            'veterinary technician',
            'water treatment plant operator',
            'weaving machine setter',
            'web developer',
            'zoologist'
        ]
    }
});
